[package]
name = "fastnanoid"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fastnanoid"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.1"
rand = "0.8.5"
