[package]
name = "fastnanoid"
version = "0.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fastnanoid"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.1"
rand = "0.8.5"

[dev-dependencies]
rstest = "0.25.0"
